apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: node-db
  name: node-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: do-block-storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: node-ipc
  name: node-ipc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage