---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      name: postgres
  clusterIP: None
  selector:
    app: postgres

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12.4
          env:
            - name: POSTGRES_LOGGING
              value: "true"
            - name: POSTGRES_DB_FILE
              value: /run/secrets/postgres_secret/POSTGRES_DB
            - name: POSTGRES_PASSWORD_FILE
              value: /run/secrets/postgres_secret/POSTGRES_PASSWORD
            - name: POSTGRES_USER_FILE
              value: /run/secrets/postgres_secret/POSTGRES_USER
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /run/secrets/postgres_secret
              name: postgres-secret
              readOnly: true
            - mountPath: /var/lib/postgresql/data
              name: postgres
              subPath: postgres
      restartPolicy: Always
      volumes:
        - name: postgres-secret
          secret:
            secretName: postgres-secret
        - name: postgres
          persistentVolumeClaim:
            claimName: postgres-pvc
      tolerations:
        - key: "4gb"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
---

