---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: postgres-pvc
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
  storageClassName: do-block-storage